---
version: 2
updates:

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /services/postgres/Dockerfile
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
