---
version: 2
updates:
  ### APPLICATION ###
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: daily
      time: 06:00
      timezone: Europe/Paris
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /services/inngest/Dockerfile
    schedule:
      interval: daily
      time: 06:00
      timezone: Europe/Paris
