services:

  app:
    build:
      context: app
      target: development
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/app?schema=public
    ports:
      - '3000:3000'
    volumes:
      - ./app:/opt/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build: services/postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "app", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    restart: unless-stopped
    profiles: [adminer]
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - '8080:8080'
