services:
  app:
    build: ./app
    environment:
      - INNGEST_DEV=1
      - INNGEST_BASE_URL=http://inngest:8288
    ports:
      - '3000:3000'
    volumes:
      - ./app:/opt/app
  inngest:
    build: services/inngest
    command: 'inngest --prod dev -u http://app:3000/api/inngest'
    ports:
      - '8288:8288'
