services:

  app:
    build:
      context: app
      target: development
    environment:
      - INNGEST_DEV=1
      - INNGEST_BASE_URL=http://inngest:8288
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/app?schema=public
    ports:
      - '3000:3000'
    volumes:
      - ./app:/opt/app
    depends_on:
      postgres:
        condition: service_healthy
      inngest:
        condition: service_started

  inngest:
    build: services/inngest
    command: 'inngest --prod dev -u http://app:3000/api/inngest'
    ports:
      - '8288:8288'

  postgres:
    build: services/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "app"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
