version: '3'

includes:
  prisma: tasks/prisma.yml

tasks:
  init:
    desc: Initialize the project
    deps:
      - init-env
      - docker-build
      - npm-install

  start:
    desc: Start the project
    deps: [init]
    cmds:
      - cmd: docker compose up --detach
      - task: prisma:deploy

  init-env:
    desc: Copy default environment variables
    run: once
    cmd: cp .env.dist .env.local
    ignore_error: true
    dir: app
    status:
      - test -f .env.local

  docker-build:
    desc: Build the Docker image
    run: once
    cmd: docker compose build

  npm-install:
    desc: Install the dependencies
    deps: [docker-build]
    cmd: docker compose run --no-deps --rm app npm install --ci
    sources:
      - app/package.json
      - app/package-lock.json
      - app/prisma/schema.prisma
    generates:
      - app/node_modules/**/*
      - app/prisma/generated/**/*
