---
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: docker compose build app

      - name: Install dependencies
        run: docker compose run --no-deps --rm app npm install

      - name: Lint code
        run: docker compose run --no-deps --rm app npm run lint
