---
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.test.yaml

    strategy:
      fail-fast: false
      matrix:
        cmd: [lint, type-check]

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: docker compose build app

      - name: ${{ matrix.cmd }}
        run: docker compose run --no-deps --rm app npm run ${{ matrix.cmd }}
